### ISSUE TITLE
After update doesn't work

### ISSUE THREAD

**Issue by studiocasaliggi** [danielbrodin/atom-project-manager#137]
I have update to 2.0.1 version and now the plugin doesn't work, it doesn't appear under the menu packages, and the keybinding not work

**Comment by danielbrodin** [comment]
Have you tried restarting atom?

**Comment by JSn1nj4** [comment]
I have this same issue. The menu item doesn't appear, but after restarting Atom the keybinding does work.

What I'm using:
- Windows 10
- Atom 1.0.8

**Comment by danielbrodin** [comment]
I'm sorry, thats my fault. I removed the menu during the rewrite of the package and forgot to add it back since I never use it. I think it's faster to use it through the command palette

**Comment by JSn1nj4** [comment]
I guess once you have the muscle reflexes for the command pallet. I honestly almost always use the "List Projects" command myself, but since that and some other commands I use have keybindings I usually don't use the command palette. Probably about the same for others.

Thanks for the quick fix though. This is honestly my favorite Atom package right now.

**Comment by danielbrodin** [comment]
Glad you liked it :)
