### ISSUE TITLE
Improve documentation of project.cson fields

### ISSUE THREAD

**Issue by guiraldelli** [danielbrodin/atom-project-manager#141]
I'd like so much to use this project to do in Atom what was bread-and-butter in SublimeText: define [project options](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/file_management/file_management.html?highlight=file_include_patterns#the-sublime-project-format).

Is it possible to improve the documentation (maybe using [ReadTheDocs](https://readthedocs.org/)) describring common options, such as _glob patterns to exclude_? (I am particularly searching for a way to do it. :grin:)

Cheers and congratulations! :+1:

**Comment by danielbrodin** [comment]
I have improved the read me some, only up here on GitHub still, not released so can't see it in Atom yet, but everything is pretty much handled from the `settings`, so if you look in Atoms `config.cson`, or the Settings view, you can find the setting you want. I guess you would want the `core.ignoredNames` setting?

From what I understand you want better documentation for what can be changed under `settings`, but not sure I can do anything about that since it is handled by Atom and each package. Or do you have any idea of how to improve it?

**Comment by guiraldelli** [comment]
>  I guess you would want the core.ignoredNames setting?

Exactly that! But I found out that I also have to turn on some properties of atom/tree-view in order to make `core.ignoreNames` and `core.excludeVcsIgnoredPaths` work: `"tree-view".hideIgnoredNames: true` and `"tree-view".hideVcsIgnoredFiles: true`, respectively.

> From what I understand you want better documentation for what can be changed under settings, but not sure I can do anything about that since it is handled by Atom and each package. Or do you have any idea of how to improve it?

I like the idea of creating a wiki with entry-level tutorials and another page of *parameters that can be used*, which could show some examples similar to the [The .sublime-project Format](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/file_management/file_management.html?highlight=file_include_patterns#the-sublime-project-format), which would include descriptions of the most commonly used (in your opinion) parameters as well as reference to pertinent Atom documentation (*e.g.*, [Global Configuration Settings](https://atom.io/docs/v1.0.11/using-atom-basic-customization#global-configuration-settings)).

That's my opinion, at least. :grin: What do *you* think? :grinning:
