### ISSUE TITLE
Implement "Close project"

### ISSUE THREAD

**Issue by alexandernst** [danielbrodin/atom-project-manager#144]
Maybe implement a "Close project" option that would close all tabs.

**Comment by danielbrodin** [comment]
A function to just close all tabs, or do you mean remove all folders from the tree-view and such too?

**Comment by alexandernst** [comment]
Yes, a function that would act pretty much as a "switch to another project" or "start an empty project".
My idea is to use that function when I want to save and close the current project (which, ideally would save a list of the opened files, scroll position, cursor position, etc and restore them when I open the project again) .

**Comment by danielbrodin** [comment]
This would also make it possible to open a new project in the current window instead of having to open a new window, but unfortunately I haven't found a solid way to do this.
But if anyone does, I would happily add this

**Comment by alexandernst** [comment]
What is the problem exactly? You aren't able to list the current tabs? You can't fetch the cursor position of each tab? You can't close the tabs?

I can open as many bugs/feature requests in Atom's issues page as you might need :)

**Comment by danielbrodin** [comment]
None of those things are a problem since Atom saves that when the window is shut by itself. The problem is to completely close the project in the current window, because the project is more than just the tabs opened and the folders in the sidebar, is has a state and things that packages rely on, so thats why it would have to be completely shut down so when running atom.open() on a path it will open the project in the current window instead of opening a new one.

Please open a feature request for it if you want. Would make many project-manager users happy if this could be solved :)

**Comment by alexandernst** [comment]
I'm still not really sure *what* exactly the problem is. What do you mean by `completely close the project in the current window`? Is that the `remove folder` from the tree-view? Or what do you actually expect an hypotetical `closeProject()` function in Atom's plugins's API to do?

**Comment by davibe** [comment]
There is a plugin called project-sidebar which is able to switch project in the same window. I am not sure what it does tho. I don't see "recent open files" pop up when i switch project instead the tabs remain the same. Worth exploring ?

**Comment by danielbrodin** [comment]
Well Atom does some things before it opens a project, like if it has already been open before it opens up old tabs and if packages saves anything in the projects state it will receive that upon opening it etc... So a `closeProject()` would have to reset Atom to a blank state so that when the new project opens it will receive all the treatment it needs. Better than a `closeProject()` would probably be using `atom.open()` but with no paths and a `useCurrentWindow` option or something though.

project-sidebar kind of breaks a project actually because what it does is replace the projects paths, so next time you open the project without using project-sidebar you will get the wrong folders for that project.

**Comment by alexandernst** [comment]
So, I created a new issue [here](https://github.com/atom/atom/issues/8962), turns out we're waiting for https://github.com/atom/atom/issues/6984 to get implemented.

**Comment by mehcode** [comment]
Yeah. Trying to do this without atom/atom#6984 will be a maintenance headache. Example: https://github.com/danielbrodin/atom-project-manager/pull/18 (my pull request to this project that does this). That PR no longer works. Here is another one to another project (that may no longer work now): https://github.com/mehcode/atom-git-projects/blob/master/lib/git-projects.coffee#L93-L140

**Comment by douggr** [comment]
2d02bde just ignores if `closeCurrent` is set or not. But a4eeed7 would work as expected, imo :)

**Comment by frenchbread** [comment]
+1

**Comment by Klortho** [comment]
+1

**Comment by mlaxwong** [comment]
any update on 'Close Project' ?

**Comment by rwatts3** [comment]
Two years later, just checking to see if there is any progress , or word on whether or not this feature will be added.

**Comment by PHLAK** [comment]
I would also like to see this feature. I'm attempting to move to Atom from Sublime Text and sometimes I just need to close out a project for one reason or another. I would expect this to save the state of the current project, close all tabs and remove all projects/folders from the side-bar.

**Comment by MvGulik** [comment]
As (second time) Atom starter. The Atom project-part handling, to me, seem a mystifying subject.

There are in my view, when it comes to user-friendliness, two options.
Using an implementation that makes general sense to the none expert user.
Or ... make sure its properly documented.

(Good documentation in general also would serve as a good intended behaviour guide. Making it easier to differentiate between what might be a bug (_unintended feature/behaviour_) or not.)

**Comment by dylan-k** [comment]
I came here looking for a "close project" feature, didn't find it here, but I did find this, which I'm posting for the benefit of any future travelers arriving here.

https://atom.io/packages/project-plus
