### ISSUE TITLE
Cannot use 'in' operator to search for 'global' in null

### ISSUE THREAD

**Issue by DaveEveritt** [danielbrodin/atom-project-manager#159]
After loading Atom, I hit cmd-ctrl-p and selected the project I want. But what appeared was a directory for a website that isn't in my list of projects. When I repeated the command and successfully launched the desired project, this error appeared:

Failed to load projects.cson
Cannot use 'in' operator to search for 'global' in null

**Comment by danielbrodin** [comment]
Do you use, or have used a package like project-sidebar that opens a new project in the same window instead of opening a new window? That kind of packages can mess up your projects paths.

Getting the error about the projects.cson would mean that it's not formatted correctly. Download a coffeescript linter and you should be able to find the error easily.
