### ISSUE TITLE
Per project plugin command setup

### ISSUE THREAD

**Issue by pedro93** [danielbrodin/atom-project-manager#178]
The title says all, I do not know if this is currently possible but could there be a tag in project settings where we could specify that a certain key stroke would apply a plugin command?
For instance: cmd_b: gcc_build for a c/c++ project.
Also the possibility to be able to create language-specific template settings based on plugins could be very easily achieved with this. 
In the current state is this possible? Is it in the backlog?

**Comment by danielbrodin** [comment]
There is no setting for project specific keybindings and I haven't really considered it since I think it's kinda weird having that. Language specific keybindings on the other hand is available within atom. Just add a keybinding that targets the scope you want and it will only work for that language.

You can however add language, or scope specific settings, it's in the read me.
