### ISSUE TITLE
Project Manager automaticaly change projects.cson

### ISSUE THREAD

**Issue by bigslycat** [danielbrodin/atom-project-manager#221]
DIFF of this changes:
```DIFF
       editor:
         tabType: "hard"
 "rbt-default":
-  group: "RBT"
-  template: "rbt-legacy"
   title: "rbt-default"
   paths: [
-    "~/dev/rbt/default"
+    "/home/cat/dev/rbt/default"
   ]
+  settings:
+    "*":
+      whitespace:
+        ensureSingleTrailingNewline: false
+        ignoreWhitespaceOnCurrentLine: true
+        ignoreWhitespaceOnlyLines: true
+        removeTrailingWhitespace: false
+    ".html.php.text":
+      editor:
+        tabType: "hard"
+  group: "RBT"
+  template: "rbt-legacy"
 "rbt-stable":
   group: "RBT"
   template: "rbt-legacy"
```
`Settings` in this diff if defined in template "rbt-legacy".

**Comment by danielbrodin** [comment]
When does this happen?

**Comment by skisulli** [comment]
This is happening to me when I open a project where the path starts with `~/`. Project manager will edit the projects.cson file and change the path to start with `/Users/USER/`. This is a problem for me as I would like to sync my projects across 2 computers that have different users. I have the source files in the same place, so `~/src/PROJECT_PATH` should work.

**Comment by V0idExp** [comment]
makes it impossible to use project manager on Linux and Mac machines, cause home directories are located in different paths

**Comment by WebAppNut** [comment]
Also does not work it using $HOME instead of ~/.

During interim, you could create an alias that uses sed to edit path on fly and invoke atom when done. This has worked for me over vboxsf, NFS and unison shares between OSX & Ubuntu/Debian:

1. Set up projects using full path to your home
2. Close Atom
3. Create aliases...

# run this on your mac per-terminal, or permanent via ~/.bash_profile
alias atom2="sed -i '' 's/home/Users/g' ~/.atom/projects.cson && atom"

# run this on your linux per-terminal, or permanent via ~/.bashrc
alias atom2="sed -i s/Users/home/g' ~/.atom/projects.cson && atom"

Note, sed on mac needs the single quotes after the -i switch

**Comment by danielbrodin** [comment]
Ok, now I get the issue. This is because Atom only works with absolute paths so I have to make the path absolute before I give it to Atom. This also leads to the absolute path being saved. Could probably use a method to get the paths before sending it to Atom instead of using the "raw" value which on save would keep it as is.

So @WebAppNut comment about $HOME not working is because I simply have to manually replace `~/` with nodes `os.homedir()`.

A "tricky" part however is how to handle adding and removing root paths in a project since currently if you add a new path, I just replace the current path(s) with the new which would also break it. I have been thinking about adding a setting which would always save the paths as relative to the `os.homedir()`. Or perhaps a setting on the project incase someone would want to have an absolute path to one project for some reason.

What's your thoughts about this?

**Comment by rsullivan-gpsw** [comment]
That seems reasonable. I always put my code somewhere in my home dir, so an option to be relative to `os.homdir()` would work for me.

**Comment by skisulli** [comment]
That seems reasonable. I always put my code somewhere in my home dir, so an option to be relative to `os.homedir()` would work for me.

**Comment by WebAppNut** [comment]
I like the idea of paths relative to home too, as long as we can also go up using double-dot notation.
