### ISSUE TITLE
Project-Manager (or Atom?) is changing paths with relative user-directories in my projects.cson

### ISSUE THREAD

**Issue by dkerzig** [danielbrodin/atom-project-manager#235]
Hey,
I work on two different computers (and sync my `./atom` folder) and I tend to place projects I work with on the same directory (`~/Developer/project-a`). And unfortunately on my work-machine the user-directory is called different from my one at home, so using the tilde in `~/Developer` is actually mandatory for me.

When I put this path (e.g.`~/Developer/project-a`) into my `projects.cson` everything works fine until I open the project from the project list for the first time, then it changes it to `/Users/name-a/Developer/project-a` depending on which machine I am currently working on.

So I tried to reproduce this in safe-mode (opening the folder of the project) but it doesn't change anything in `projects.cson` so I am wondering if you could help :)

Regards from Germany,
Dennis

**Comment by danielbrodin** [comment]
It's the project manager that is changing it because atom only accepts absolute paths. There have been talks about this before where I think we ended up with the idea to add a setting for if you want to use absolute or relative paths. I have had a lot to do lately though so I haven't had the time to implement it.
Last discussion was here https://github.com/danielbrodin/atom-project-manager/issues/221
