### ISSUE TITLE
Can't set the tab type for a project

### ISSUE THREAD

**Issue by jasperkennis** [danielbrodin/atom-project-manager#237]
I'm trying to set the softTabs setting to false in order to get actual tabs in my .scss files. I have the following config:

``` shops:
  title: "Shops"
  paths: [
    "/Users/jasperkennis/Desktop/shops/shop"
    "/Users/jasperkennis/Desktop/shops/themes/theme"
  ]
  settings:
    '.scss':
      'editor.tabLength': 2
      softTabs: false
```

But .scss files keep using two spaces instead of tabs. Am I doing something wrong?

**Comment by danielbrodin** [comment]
Have you tried `editor.softTabs: false`?

**Comment by jasperkennis** [comment]
Yeah. I have this now:
```
name:
  title: "Name"
  paths: [
    "path1"
    "path2"
  ]
  settings:
    ".scss":
      "editor.tabLength": 2
      "editor.softTabs": false
    ".source.scss":
      "editor.tabLength": 2
      "editor.softTabs": false
    ".source.sass":
      "editor.tabLength": 2
      "editor.softTabs": false
    ".source.css.scss":
      "editor.tabLength": 2
      "editor.softTabs": false
    ".sass.source":
      "editor.tabLength": 2
      "editor.softTabs": false
```

But still no luck:(

**Comment by lzkelley** [comment]
I'm not sure if this is the same problem, but I wasn't able to set the preferred line length.  I found that the issue seems to have something to do with having multiple projects open at once (and which opens first/last or something).  The setting from the local `project.cson` file is getting saved to the global `~/.atom/config.cson` file -- and then that is overriding the other `project.cson`.  So if I open a single project, its settings are being respected.  But once I open another one, the settings get overwritten.  I'm not sure if this is the intended behavior.

**Comment by danielbrodin** [comment]
Atom currently doesn't have a way to do real project specific settings and unfortunately the settings is saved as soon as any setting is saved, so it should work as long as you don't trigger any settings save.
I think project specific settings is being worked on, which will make it easier to implement
