### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by danielbayley** [danielbrodin/atom-project-manager#275]
I just thought rather than have `group:` (or in addition to…) there could be an array of `tags: []` which would be searchable.

**Comment by danielbrodin** [comment]
This is something I have been thinking about too, but wasn't sure anyone had the need for more than one tag (the group), so didn't implement it. 

Replacing it would be hard since that would remove the option to sort by group.

Another thing would be that the filter that is being used only have support to filter by a direct value in an object, not an array, but that could probably be fixed by giving the filter an `array.toString()` or something.

**Comment by chopra-austin-west-mec** [comment]
can you have it so were i can type for example`node, assignment, project, school` and  have it where i can search one of those, the way i add tags to a project is i add the section that i am working on in school, and if it is an assignment and project, and wether it for school, work, or fun.
