### ISSUE TITLE
Overlapping projects

### ISSUE THREAD

**Issue by rdebeasi** [danielbrodin/atom-project-manager#291]
I'd like to create a few projects that share some directories. Currently, project manager doesn't seem to distinguish between the projects. Could support for "overlapping" projects be added in the future? Am I missing a step? Thanks!

I'd like to create these projects:
- Theme only
- Theme plus a specific plugin
- Theme plus all plugins

Creating the "theme only" project works fine. When I open the theme and a plugin (or the theme and all plugins) and try to save this setup as a new project, Project Manager instead opens a dialog to edit (and overwrite) the first project.

**Comment by danielbrodin** [comment]
A project is identified by it's root path so my guess is that you have the theme path come first for each project? 

A project needs some sort of identification to be able to update itself when the `projects.cson` file is updated, and since that change could be a change to the paths of a project the root path is the only thing that can identify it correctly. 

So if you can have a unique root path your problem should be solved.

**Comment by rdebeasi** [comment]
Got it, thanks! The theme path does come first for each project. I assume that the directories were sorted in alphabetical order and then saved by Atom Project Manager.

I was able to get the setup I wanted by editing projects.cson manually, but there doesn't appear to be a way to resolve the issue using the commands available from the command palette. In addition, the "theme only" project doesn't seem to work. It's listed correctly in the project menu, but when I try to open it, I get the "theme + fancy plugin" project instead.

Perhaps a future version of atom-project-manager could give each project a unique ID to avoid this sort of ambiguity. A unique ID might also prevent problems if the root path of the project ever changes. Or, maybe this is such an edge case that it's not worth worrying about! 😃 Either way, thanks very much for your help.

For what it's worth, here's my `projects.cson`:

```cson
# The first element in the paths array identifies the project. So, put any
# shared directories (such as /themes/stat) at the end of the paths array.

[
  {
    title: "STAT Everything"
    paths: [
      "/Users/debeasi/Projects/stat/www/content/dist/plugins"
      "/Users/debeasi/Projects/stat/www/content/dist/themes/stat"
    ]
  }
  {
    title: "STAT Fancy Plugin + Theme"
    paths: [
      "/Users/debeasi/Projects/stat/www/content/dist/plugins/stat-fancy-plugin"
      "/Users/debeasi/Projects/stat/www/content/dist/themes/stat"
    ]
  }
  # The following doesn't work - APM opens "STAT Fancy Plugin + Theme" instead of just the theme.
  {
    title: "STAT Theme Only"
    paths: [
      "/Users/debeasi/Projects/stat/www/content/dist/themes/stat"
    ]
  }
  {
    title: "WordPress Core"
    paths: [
      "/Users/debeasi/Projects/stat/www/core"
    ]
  }
]
```

**Comment by fievelk** [comment]
It will soon be possible to move project folders in atom tree view (see atom/tree-view#525).
Will this affect `atom-project-manager` projects?

I personally think that it is not the best thing to consider the root path as the unique identifier for a project. I always work with a `notes` folder in my project, and it comes first for each project I am working on. So this prevents me from saving new projects using `atom-project-manager`.

https://github.com/atom/tree-view/pull/525

**Comment by danielbrodin** [comment]
Yes, this will affect the projects. Not in a major way, but currently, if the root path changes a new project will be added.

I guess this could be solved by adding a `id` key to each project. It's not foolproof since someone editing the `projects.cson` file could change the `id`, which did happen before 2.0 where each project did sort of have an ID.

I think Atom handles it by just creating an ID based on all the paths and creating a new file when the paths is changing and they save the state. This works though since those files isn't edited manually so they can handle it how they want.

Any other ideas about adding a unique identifier than simply having an `id` key on each project?

**Comment by fievelk** [comment]
@danielbrodin Even if an `id` key would not be foolproof, I think it would still be preferable than using the path as identifier as it is now (especially in the light of atom/tree-view#525).

**Comment by fievelk** [comment]
@danielbrodin has this been fixed?
