### ISSUE TITLE
Project Root file?

### ISSUE THREAD

**Issue by flyinbutrs** [danielbrodin/atom-project-manager#293]
I have a feature request...  So there's currently an option to have it search the default projects path and include all .git repos. I have a number of projects that include multiple related repos, and they're generated from a template. I'd love to include a file that's like... ".project" and have it look for those files the same way it looks for .git and include those paths as a project. Ideally as a separate option from .git, because I would turn off .git loading if there was .project loading.

Thoughts? Is that clear?

**Comment by danielbrodin** [comment]
Yes, this is something I have been wanting to add. There is already support for having a local `project.cson` file that will be used if the project is open, there is no support for searching for projects with it though.

Adding the search for it is pretty easy, but there is some other things that needs to be done as well like saving the settings to the local file instead of the global `projects.cson` if you run a `Project manager: Edit Project`.

It would of course be a separate option. So it will come, I just haven't had time to work on it :)
