### ISSUE TITLE
Allow project to be opened in current window

### ISSUE THREAD

**Issue by jmacdonald** [danielbrodin/atom-project-manager#34]
I use Atom in full-screen mode, and the attractive bit about switching projects is the idea that I can do so without creating another space/virtual desktop. If there was a setting to replace the current project instead of creating a new window, that'd be great.

**Comment by kostko** [comment]
Is there a ticket open in the atom issue tracker that would need to be resolved in order for this to be supported?

**Comment by 21xhipster** [comment]
That us the most annoying thing in Atom.. 
I use to switch between projects in Sublime without changing anything around.. But the way projects works in Atom sucks... I'll just repeat the question above:
> Is there a ticket open in the atom issue tracker that would need to be resolved in order for this to be supported?

**Comment by dorian-marchal** [comment]
Same question, here :

> Is there a ticket open in the atom issue tracker that would need to be resolved in order for this to be supported?

**Comment by rolfkleef** [comment]
The project-sidebar plugin builds on project-manager and seems to be able to do this: https://atom.io/packages/project-sidebar

**Comment by danielbrodin** [comment]
Just took a quick look at the code and it seems like that plugin simply removes the current folders and adds some new which I believe takes away some functionality like loading previously opened files and probably (not sure) the projects state which some packages rely on.

About an issue ticket for this, I have no idea. If not, anyone is welcome to add one :)

**Comment by rolfkleef** [comment]
Yes, it doesn't open or close editors or other panes or maintain project state, so it's not a full context switch... When you switch to a file from another project folder, that folder is added again to the tree view. But seems to work a bit to help me re-focus :-)

**Comment by optikalefx** [comment]
+1 on this. I'm not sure what native wrapper Atom is using for it's JS. But whatever it is you'd have access to the native OS windowing. You should easily be able to close the previously open window. I know MacGap and NW.js both support this. 

As a 2nd suggestion. I can tab to that old window and close it with cmd w. Could we just add a sort of macro on that OS that you fire off that would tab to the previous window and close it?

**Comment by danielbrodin** [comment]
The `close current` setting used to close the current window when opening a new, but after an update to Atom it stopped working because the window closed before Atom managed to open the new window. I didn't manage to get it working so now it's disabled.

**Comment by optikalefx** [comment]
Yea but whatever atom is using has full access to a widow manager. There
should be no reason why you can't cycle through and work with both windows
at your timing Leasure. If you give me a starting place I can dive in.

**Comment by cuth** [comment]
I think it is related to this issue:

https://github.com/atom/atom/issues/5138

**Comment by samu** [comment]
:+1:

**Comment by webcaetano** [comment]
still nothing?

**Comment by danielbrodin** [comment]
@webcaetano not that I'm aware of

**Comment by vannleonheart** [comment]
My computer takes several minutes to open new editor when switching to other project. It will be better if there is an option when I open other project it will automatically add project folder in current editor window. Thanks.

**Comment by mehcode** [comment]
@danielbrodin 

I've figured out how to do this (I had a PR a while back with a hacked to hell version). You can deserialize project state from an object (which you could construct yourself or read from atom's own state store; it contains paths, buffers, etc.) and the editor magically "switches" to that project in-window. I've only noticed a few issues from this approach (which basically stems from some packages do not listen properly to when a project is deseralized -- most seem to work alright though).

You want to look at the `atom.project.deserialize` function for what to call when you want to "switch" projects in-window. If you first read from atom's state store you can get open tabs / buffer selection / unsaved work / etc. as well.

I've implemented this approach in https://github.com/mehcode/atom-project-plus -- I was originally working on another PR to this (and I still might make one) but as I dug into it more I found it odd how this package has its own project > paths mapping (when atom already has one); so, I ripped that out and it became its own package.

**Comment by danielbrodin** [comment]
I remember the hacked to hell version :) But nice that you figured it out. Will have a look at your package when I have the time unless you want to PR it.

> I found it odd how this package has its own project > paths mapping (when atom already has one)

Not sure what you mean with this though. The paths array is needed to tell Atom which project to open?

**Comment by mehcode** [comment]
> Not sure what you mean with this though. The paths array is needed to tell Atom which project to open?

Atom remembers every "path array" ever opened in its state store. You can enumerate this list of path arrays and present that as the list of available projects, sorted by last accessed. This is what project-plus does.

**Comment by danielbrodin** [comment]
That is nice, I do however like to decide what projects I have in my list since I open a lot of things just once, and if you have a bug in Atom and have to remove the storage all projects would be gone.

Having a fast look at your code it seems like we would just have to migrate some of the things in `utils.coffee` and it should work. Think I can find some time in a moment to try it out :)

**Comment by danielbrodin** [comment]
I have done a quick test of migrating some of the code to the package and it seems to work pretty well. Will have to test it a bit more though and refactor it before a release, but really nice work :)

**Comment by danielbrodin** [comment]
@mehcode I managed to get it working pretty fast, but when the 1.7 beta was released it stopped working. Would you mind having a look at the [feature/switch-project](https://github.com/danielbrodin/atom-project-manager/tree/feature/switch-project) branch? I have manually converted your coffeescript to ES6 so could have missed something there or something happened in the update. I have had a bit different approach to the <= 1.6 and 1.7 in that I have created a `shims.js` that is basically a "fake" atom object so it can easily be removed by just changing `_atom` to `atom` when 1.7 is released. The `switchProject` function is still in a `utils.js` though.

Have been thinking about your approach in just using the state store as the database instead of a `projects.cson` and realized that it could probably pretty easily be implemented since I have separated the database part into it's own file, so with just a setting there could be two databases. One using `projects.cson` which would be the current one, and one using the state store. The state store database would just have to find the project states like you do now and then return the data that is needed for a project (`project.js`) which would be a title and paths so it can be listed. Could probably be a nice feature.

**Comment by mehcode** [comment]
@danielbrodin I implemented your second paragraph inside of project-plus. "Auto discovery" is now configurable. What do you think about https://github.com/mehcode/atom-project-plus/issues/28 ?

---

As for why it's not working for you in 1.7.. I don't know. First guess was the API change but you seem to have caught that too (or you started after I did; https://github.com/danielbrodin/atom-project-manager/blob/feature/switch-project/lib/utils.js#L11 ). I'd have to know more about why it stopped working to help. The code I have has only broken a couple times and that was due to master being updated (as I was targeting master). 

I'd have to assume that something in your shim is off. I stared at it for ~15 minutes and I don't _see_ anything that is off. I did notice https://github.com/danielbrodin/atom-project-manager/blob/feature/switch-project/lib/utils.js#L18 -- compared to -- https://github.com/mehcode/atom-project-plus/blob/master/lib/util.coffee#L172

If I find some time later I'll actually try running it but I'm off to :zzz: for tonight.

**Comment by scowalt** [comment]
I believe this got implemented with d205d95e057318c191eb2a10b728918ff98e5a00.

Should this issue be closed?

**Comment by JustinAiken** [comment]
The 'open-in-window' part of 3.0 is working great for me :)

**Comment by danielbrodin** [comment]
@scowalt Yes it should :)
