### ISSUE TITLE
File tabs no longer visible after switching project without opening new window

### ISSUE THREAD

**Issue by V1nzi** [danielbrodin/atom-project-manager#363]
Hello,

whenever I use shift-enter to open a project in the current window of atom, the file tabs and the "Project"-heading in the tree view go missing.

So the steps to reproduce should be:
- Open atom
- Switch to a project without opening a new window

**Expected:**
I can see the "Project"-heading in the tree view and the file tabs as soon as I open a file.
**Actually:**
I can't see the "Project"-heading in the tree view nor the file tabs as soon as I open a file.

Atom: 1.19.6
Electron: 1.6.9
OS: Windows 10 64-bit
Project-Manager: 3.3.5

Images:

Project view after switching to project in new window of atom:
![atom_tabs_visible](https://user-images.githubusercontent.com/21370345/30150879-6e9fce6c-93ad-11e7-8f6c-a687036c7df9.PNG)

Project view after switching project with shift-enter (no new window):
![atom_tabs_missing](https://user-images.githubusercontent.com/21370345/30150880-6ea100a2-93ad-11e7-87e0-2a047f6b13f6.PNG)

**Comment by fa-persien** [comment]
I'm experiencing the same issue on

 - Linux Mint 18
 - Atom 1.12.6
 - Project Manager 3.3.5

**Comment by balderclaassen** [comment]
I have this issue too. While it would be great if it could be fixed, I have found a quite simple workaround. ( that works on my machine anyway). When I open a project and this happens (seems to happen if I haven't opened the project yet since booting up atom) I move back to the project I was in, which does have tabs, then back to the project which didn't show tabs and now it does. 
So basically, it seems tabs are hidden the first time a project is opened (after a boot of atom) and switching out and back into the project will show the tabs as normal.


Atom: 1.20.0
project-manager: 3.3.5
OS: Ubuntu Gnome 17.04 64bit

**Comment by mmn6d6d6e** [comment]
#348

**Comment by mmn6d6d6e** [comment]
@balderclaassen i don't seems able to make your fix works.

1. open atom
2. switch to other project
3. tabbar & treeview header gone
4. switch back to previous project
5. tabbar & treeview still missing (?)

am i doing it wrong?

**Comment by balderclaassen** [comment]
Well for me this happened when I was in a saved project, with proper tab bar. Then I went to an automatically detected git project(any project with a .git folder that you didn't add specifically), the tabbar was missing. I went back to my saved project, with the tab bar, and from now on, going to that particular git project worked too.

Maybe you are in a different situation though ? 
A restart of Atom and Ctrl+Shift+P Projects manager "reload projects list" ( or something similar) might help as well.
