### ISSUE TITLE
Is this package still being worked on?

### ISSUE THREAD

**Issue by robhuska** [danielbrodin/atom-project-manager#369]
I am just curious if the current owner/developer of this package is still interested in working on it. I have not seen any updates for several months and there have been quite a few bugs that have come up that have not had any sort of resolution. I have not even seen the author @danielbrodin comment on any of the issues for a long long time.

I do not have the skill set to maintain this type of plugin, but maybe someone out there does and could talk about transferring the ownership to someone that has the time to take this project on. I understand that peoples lives change and maybe the original author lost track of it. Just trying to spark a conversation to help keep this package alive because it is one I use on a day to day basis and the other alternatives that I have tried are far worse than this.

Thanks all!

**Comment by danielbrodin** [comment]
I'm really sorry for not answering issues, but I haven't had time to work on this lately and the last months I have used vscode instead of atom.

We had a discussion here https://github.com/danielbrodin/atom-project-manager/issues/345 about moving the package to a [atom-project-manager](https://github.com/atom-project-manager) group and move all parts out to their own packages to make it easier for others to contribute and work together on it, but I haven't had time to do anything and I don't think @mehcode have done much either except for setting up the basics.

I really would like to keep working on it, but just haven't had the time :/

**Comment by xh3b4sd** [comment]
Is there an alternative to this project we can use instead? Number of issues grows and when it is not maintained the project will become useless over time. I would like to have an alternative to this project since I find it quite essential for my daily workflow.

**Comment by Ray-B** [comment]
Just as a general comment, I noticed the slowdown in contributions as well. The package is actually so far behind now that it's having a detrimental effect on atom performance in some cases, which will really turn people off of what I see as a very useful package. 

For example, if you use the latest version of this package, combined with file-icons, there is a case where you can end up with package load times exceeding 10 seconds. 

Would be nice to see this package continue to live. @danielbrodin curious what you think the best course of action is here.

**Comment by alflanagan** [comment]
As of the 1.26.0-beta, there's a core package that provides some project features:
https://github.com/atom/atom/pull/16845

Don't know how it compares feature-wise, it does use quite different config files.
