### ISSUE TITLE
Switching between projects forces editor to lose focus

### ISSUE THREAD

**Issue by jeffreysbrother** [danielbrodin/atom-project-manager#375]
Atom version 1.23.3
Project Manager version 3.3.5

Switching back and forth between projects would, ideally, retain or force focus onto the previously-selected open file.

Many users, including myself, do not use the mouse very frequently ... in its current state, the plugin forces users to apply focus on an open file in order to switch tabs, scroll down the page, or make a change.

That being said, I've been using Project Manager every day for about a month now. Thanks a lot for the useful tool!

**Comment by xh3b4sd** [comment]
I have this issue as well in version `3.3.8`. Why was this issue here closed without information given? Is there a way to configure or regain focus after switching projects? See my atom version below. I also use the project manager extensively for a long time now and my workflow relies quite heavily on it. My current workaround is to toggle focus via a key mapping that I have to press twice because it cycles through tree view first and then focuses the editor. Any hints highly appreciated 🙈 

---

```
$ atom --version
Atom    : 1.46.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
