### ISSUE TITLE
Opening the same project twice actually opens the project again

### ISSUE THREAD

**Issue by mansona** [danielbrodin/atom-project-manager#395]
Howdy folks 👋 

First of all, thanks a million for the great addon. It has kept me productive for years at this stage 🎉 

I noticed the issue I'm having after https://github.com/danielbrodin/atom-project-manager/issues/393 was fixed. Essentially when I run `⌘^p` to open the project manager and open a project, then open the exact same project a second time it will **open the project twice**

I'm pretty sure the behaviour used to be that it would switch to the project that you're requesting to open if it was already open 🤔

**Comment by Anifacted** [comment]
This is happening for me as well. I end up with a lot of duplicated projects in different Atom instances. Could it be related to a recent OSX update?

**Comment by danielbrodin** [comment]
This has always been handled by atom itself since there is no way to know which instances of atom is open. So my guess would be that there have been a change in atom. Maybe something to do with the change that required the #393 fix?

Would be happy to merge a PR if someone solves this.

**Comment by Anifacted** [comment]
I see. Too bad :/ Will try to investigate.

**Comment by tjkohli** [comment]
The same issue occurs for me with `project-manager` version `3.3.7` on Atom `1.36.1` on macOS 10.14.4.

**Comment by lu-x** [comment]
I'm also affected (mac 10.14.4, atom 1.36.1).

**Comment by wuxxin** [comment]
also affected: linux, atom 1.38.2, project manager 3.3.7

**Comment by wuxxin** [comment]
project manager still at version 3.3.7 which has this issue

**Comment by madrussa** [comment]
This bug seems to stem from when there was an Atom issue in 1.36.1 which was subsequently fixed in 1.37.0 see https://github.com/atom/atom/pull/19203. 

The pull request #393 was added to fix what was then an atom issue. This doesn't appear to be the case anymore and reverting the change should fix this issue as within the atom package https://github.com/atom/atom/blob/119fead6925c0b6b30e9ce837c551bffaca42989/src/main-process/atom-application.js#L1325 passing the newWindow param will forcibly make atom open a new window, otherwise it will try to find an existing window matching the given paths.

**Comment by danielbrodin** [comment]
@madrussa fix has been merged and published.
