### ISSUE TITLE
Switching projects times out

### ISSUE THREAD

**Issue by tfrokt** [danielbrodin/atom-project-manager#412]
Most times it works great! Sometimes it takes a long time and sometimes it even times out and I have to restart Atom. I couldn't find any pattern so far. 
Happy to debug and provide more info if you let me know how. 

```
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```

`project-manager 3.3.8`

![Screen Shot 2021-08-06 at 10 05 24 am](https://user-images.githubusercontent.com/82917641/128436627-7c09fd60-6bac-4e68-b980-a8af25be87d1.png)
![Screen Shot 2021-08-06 at 10 06 03 am](https://user-images.githubusercontent.com/82917641/128436631-45a87c24-3243-4227-8369-98807b1e3487.png)

**Comment by tfrokt** [comment]
Sometimes it just takes a lot of effort (and time).

![Screen Shot 2021-08-23 at 9 40 38 am](https://user-images.githubusercontent.com/82917641/130373765-be9a7447-08f5-4b3e-bf0c-f843fa220bf3.png)

**Comment by danielbrodin** [comment]
If you open a project in a new window, that is atom opening the project. If you are opening it in the same window however, that is handled by https://github.com/mehcode/atom-project-util. This package does a lot of manual things to open the project in the same window since there is no support for it in atom, so could perhaps be something with your environment that it doesn't manage to close down?

**Comment by tfrokt** [comment]
Yes, I do open it in the same window. 
Sure it could be sth. related to my environment, especially if no one else has reported this issue. I am just wondering what it could be. Haven't done any Atom development myself, so wondering what I could check? Are there any debug logs for when switching projects?
