### ISSUE TITLE
Remember open files for a project?

### ISSUE THREAD

**Issue by lombardi-gux** [danielbrodin/atom-project-manager#89]
Would be great if (optionally) when I opened a project the last open documents were re-opened.

**Comment by brendanfalkowski** [comment]
+1 Just noticed that doesn't happen

**Comment by danielbrodin** [comment]
Atom should automatically open the last opened files, but there is a bug where it doesn't do this the first time a project is opened. Try to open the project, then open it again. This will open it in a new window with the correct files open.

An issue for this is filed in atom, but not sure what the progress for it is.

**Comment by lombardi-gux** [comment]
This is not true for me.

I launch Atom, open a project,  do some work, open some tabs.

Close project buy don't quit Atom.

Open a new blank window, so that the menu items are available.

Toggle Project Mgr, open the project from step 1.  No tabs are open.  Very annoying.

**Comment by brendanfalkowski** [comment]
Re-tested with the "save-session" package disabled. Atom doesn't remember the files that were open in my project after closing the project and re-opening [or] quitting Atom and re-launching.

**Comment by danielbrodin** [comment]
Try this
- Open atom
- Open project with the project manager
- With the project open, open it again with the project manager

It should then (at least it does for me) open the project in a new window with the correct files and tabs open.

Atom does something weird when it opens a project in an empty window

**Comment by brendanfalkowski** [comment]
Hmm, that sort of works. Opens the same project but with an older set of open files. Tried switching back and forth between new projects and that seems to hook the open files.

**Comment by danielbrodin** [comment]
Yeah, it's not how it should work, but unfortunately that is how it currently works. I think they are working on a fix for it though.

**Comment by chuyik** [comment]
@danielbrodin I think other duplicated issues like #78 #37 #27, and keep this issue open instead.
It's definitely frustrating that the opened files did not reopen and the `save-session` package didn't work well with multiple windows. However the trick you mentioned it works :joy: .

**Comment by KangarooCreativeTeam** [comment]
EPIC SUMMARY of various related issues [HERE](https://github.com/danielbrodin/atom-project-manager/issues/27#issuecomment-118113226)

I've been trying to reproduce the bug (to understand where & why it occurs). 

This is what I've come up with:

* When _any_ folder is already loaded in the sidebar, opening a project will load it's tabs correctly.
* When _no_ folder is in the sidebar (sidebar is blank), opening a project will _assign_ the current window to that project, & will _add_ the project's folder to the sidebar, but will **not** open the project's tabs
  * Then trying the double-loading trick (reloading the same project again) will not work (at least for me) because it will bring the existing window to the front (where the project has already been loaded without tabs).
* So; this experiment concludes that a possible workaround to the issue is to load any folder in the sidebar (usually automatic when dragging _any_ file to the editor).  _Then_ loading your project _will_ load it's tabs! 

(I should state; I have had the double-loading trick work at some point, but not in the steps above).

I hope the thing I pointed out about an empty window having the project folder assigned to it (without tabs), instead of opening in a new window, is useful in debugging. 

Of course; [save-session](https://atom.io/packages/save-session) seems to be the go-to solution at present...

O_O

**Comment by spencerthayer** [comment]
+1 for this.

I would love to be able to open a project folder and all the previously opened files within that project open up. When opening a new project folder the other project files vanish and the new project files open.

This is a typical function in IDEs including Brackets.

**Comment by hquadrat** [comment]
Any progress on this issue? Somewhat unexpected & frustrating behaviour that files are not reopened.

**Comment by shlomi-noach** [comment]
This seems to be working for me, but I would like to share a thing that was confusing to me: on OS/X I actually had two windows of atom opened. Whenever I closed and started Atom again, the "wrong" window would be on top: the one where my projects are not opened. Finally I realized that and a "Cmd-backtick" switched me to the "right" window, where indeed all projects were properly reopened. 
I proceeded to close the "wrong" window. 

In the hope that someone else was affected by this.

**Comment by josh18** [comment]
Is there a Atom issue that we are waiting on for this to be fixed? (In regards to Atom doing weird stuff when opening a project in an empty window).

Double opening a project doesn't seem to work anymore (for me anyways) but if you open another project folder and then open your project it does restore the files.

**Comment by gandalf3** [comment]
Still experiencing this behavior. Double opening a project doesn't seem to do anything, but opening a different project, then opening the intended project restores the correct tabs.

Opening a project directory directly with `atom path/to/project/directory` does restore tabs, but seemingly only a specific snapshot of old tabs which doesn't change. It also once loaded with some tabs from the wrong project mixed in, but I couldn't find a way to reproduce that unfortunately.
