### ISSUE TITLE
Allow to be rename the label of paths

### ISSUE THREAD

**Issue by rodrigopmatias** [danielbrodin/atom-project-manager#99]
That would be interesting to work with large projects where we have many subprojects, because often the directory name is not necessarily friendly.

**Comment by rodrigopmatias** [comment]
![github-01](https://cloud.githubusercontent.com/assets/109422/7089584/59af0bbc-df73-11e4-9233-9b57ee13eed6.png)

The sample

**Comment by Ciantic** [comment]
Also it might be required to be virtually naming the folders, to make any sense. See https://github.com/atom/atom/issues/5728 

Mr @mrameezraja has the problem he has multiple projects all named "www" he can't add them all to project because they would be all named "www".

Instead the paths should be allowed to have object:

```
'my solution'
  'paths':
    'my project' : 'C:\some\www'
    'other project : 'C:\other\www'
```

**Comment by rodrigopmatias** [comment]
this way would be beautiful

**Comment by rodrigopmatias** [comment]
The jump cat!!!

Make symbolic links with label name
![atom02](https://cloud.githubusercontent.com/assets/109422/7326875/050e62e2-ea9f-11e4-95c0-a6fa6a812e2a.png)

The result is:

![atom01](https://cloud.githubusercontent.com/assets/109422/7326865/f2a7ab54-ea9e-11e4-8cc9-33322b815896.png)

More its not beautiful

**Comment by danielbrodin** [comment]
Interesting idea, but I think the tree view package would have to add some support for this to work.

**Comment by rodrigopmatias** [comment]
inheritance and overwritten could not solve this?

Or a pull request with the code for add this feature.

**Comment by rodrigopmatias** [comment]
The issue is open in tree-view project

https://github.com/atom/tree-view/issues/453

**Comment by rodrigopmatias** [comment]
@danielbrodin can you see this project https://github.com/subesokun/atom-project-view

**Comment by GizMecano** [comment]
A related feature [seems to be also discussed](https://github.com/atom/atom/issues/9278) on the main Atom project.

Otherwise, in addition to the [Project View package](https://github.com/subesokun/atom-project-view) mentioned above, maybe it could be useful to consider [project-alias package](https://github.com/bitcula/project-alias), which announces to be able to "_rename projects and_ (shows) _a tooltip with the original name when the user hovers with the cursor over a renamed project_".
